version: '3'

services: 

  nginx:
      build: 
        context: nginx
        dockerfile: Dockerfile
      container_name: nginx
      networks: 
        - node-network
      tty: true       
      ports: 
        - "8080:80"
      depends_on:
        - app
  app:
      build: 
        context: node
      container_name: app
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
      networks: 
        - node-network
      volumes: 
        - ./node:/usr/src/app
      tty: true
      depends_on: 
        - db
  
  db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes: 
        - ./mysql:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      environment: 
        - MYSQL_DATABASE=fc_docker_node
        - MYSQL_ROOT_PASSWORD=root
      networks: 
        - node-network
networks: 
  node-network:
    driver: bridge      